[package]
name = "d3_rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# counter = "0.5.2"
# array-init = "2.0.0"
itertools = "0.10.1"
