name: Update our AoC leaderboard in a markdown table
on:
  push:
    branches:
      - 'master'
jobs:
  update_readme:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          ref: 'master'
      - name: Merge master on leaderboard
        run: |-
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "README-bot"
          git fetch origin leaderboard:leaderboard
          git merge --allow-unrelated-histories -s ours leaderboard
          git switch leaderboard
          git merge --no-ff --no-commit master
          git commit -m "Merge branch 'leaderboard'"
      - name: Update leaderboard
        run: ./update_leaderboard.sh
        env:
          COOKIE: ${{ secrets.COOKIE }}
      - name: Commit and push if changed
        run: |-
          git diff
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "README-bot"
          git add -A
          git commit -m "Update leaderboard" || exit 0
          git push origin leaderboard
          git switch master
          git merge --no-ff leaderboard
